# number of samples to generate
sample_size: 128

# 'random' for SciPy-based sampling, or 'sobol' / 'latin_hypercube' for SciPy QMC experimental design.
sampling_method: sobol
# random seed for reproducibility.
seed: 21

medium_properties:
  Host_rock:
    - porosity
    - intrinsic_permeability
    - density


