uncertain_parameters:
  rock_data:
    Zechstein:
      - porosity
      - density
    Host_rock:
      - porosity
      - density
    basement:
      - porosity
      - density
  nuclide_water_diffusivity_data:
    Zechstein:
      - I-129
    Host_rock:
      - I-129
    basement:
      - I-129

