uncertain_parameters:
  rock_data:
    Aptian:
      - porosity
      - density
    Host_rock:
      - porosity
      - density
    Valanginian_Wealden:
      - porosity
      - density
  nuclide_water_diffusivity_data:
    Aptian:
      - I-129
    Host_rock:
      - I-129
    Valanginian_Wealden:
      - I-129


